[build]
  base = "react-portfolio"
  publish = "client/dist"
  command = "npm --prefix install && npm --prefix client run build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
