[build]
  base = "react-portfolio/client"
  publish = "react-portfolio/client/dist"
  command = "npm run build"

[functions]
  directory = "react-portfolio/netlify/functions"
  node_bundler = "esbuild"
